import { hasPaymentInstructions, PAYMENT_INSTRUCTIONS } from "./payment-config.js";

const e = value => String(value ?? "").replace(/[&<>\"]/g, c => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;" }[c]));
const money = value => new Intl.NumberFormat("tr-TR", { style:"currency", currency:"TRY" }).format(Number(value || 0));
const date = value => value ? new Intl.DateTimeFormat("tr-TR", { dateStyle:"long" }).format(new Date(value)) : "—";
const dateTime = value => value ? new Intl.DateTimeFormat("tr-TR", { dateStyle:"long", timeStyle:"short" }).format(new Date(value)) : "—";
const daysLeft = value => value ? Math.max(0, Math.ceil((new Date(value) - Date.now()) / 86400000)) : 0;
const effectivePaymentStatus = row => row?.status === "pending" && row?.expires_at && new Date(row.expires_at) <= new Date() ? "expired" : row?.status;
const remainingTime = value => { const minutes=Math.max(0,Math.ceil((new Date(value)-Date.now())/60000));if(!minutes)return "Süre doldu";if(minutes>=1440)return `${Math.floor(minutes/1440)} gün ${Math.ceil((minutes%1440)/60)} saat`;if(minutes>=60)return `${Math.floor(minutes/60)} saat ${minutes%60} dakika`;return `${minutes} dakika`; };
const STATUS = {
  active:["✅","Aktif"], pending:["⏳","Ödeme bekleniyor"], receipt_sent:["🔎","İnceleme bekleniyor"],
  approved:["✅","Onaylandı"], rejected:["❌","Reddedildi"], expired:["⌛","Süresi doldu"]
};
const PLAN_NAMES = {
  FREE_STARTER:"Ücretsiz Başlangıç", FAMILY_MONTHLY:"Aile Aylık", FAMILY_YEARLY:"Aile Yıllık"
};
const REFUND_STATUS={requested:"İade talebi inceleniyor",approved:"İade kabul edildi — ödeme bekleniyor",rejected:"İade reddedildi",completed:"İade tamamlandı",cancelled:"İade işlemi iptal edildi"};
const planName = plan => PLAN_NAMES[plan?.code] || plan?.name || "Plan";

export function isAdminUser(user) {
  return user?.app_metadata?.role === "admin" && user?.app_metadata?.is_admin === true;
}

export function planCards(plans) {
  const monthly = plans.find(x => x.code === "FAMILY_MONTHLY");
  return plans.map(plan => {
    const free = plan.code === "FREE_STARTER";
    const yearlySaving = plan.code === "FAMILY_YEARLY" && monthly ? Math.max(0, Number(monthly.price) * 12 - Number(plan.price)) : 0;
    const duration = plan.duration_days ? (plan.code === "FAMILY_YEARLY" ? "12 ay" : `${plan.duration_days} gün`) : "Ücretsiz erişim";
    return `<article class="card payment-plan" data-plan-code="${e(plan.code)}"><p class="eyebrow">ÜYELİK PLANI</p><h3>${e(planName(plan))}</h3><strong class="payment-price">${money(plan.price)}</strong><p>${duration}${free ? "" : " · mevcut sürenin üzerine eklenir"}</p>${yearlySaving ? `<p class="feedback correct">Aylık plana göre ${money(yearlySaving)} avantaj</p>` : ""}${free ? `<p class="meta">Manuel ödeme gerekmez.</p>` : `<button class="button primary" data-action="select-payment-plan" data-plan-code="${e(plan.code)}">Bu planı seç</button>`}</article>`;
  }).join("");
}

export function subscriptionCard(subscription) {
  if (!subscription) return `<article class="card membership-summary"><p class="eyebrow">AKTİF ÜYELİK</p><h2>Ücretli üyelik bulunmuyor</h2><p>Ücretsiz içeriklerden yararlanabilir veya aile planı seçebilirsin.</p></article>`;
  const status = STATUS[subscription.status] || ["ℹ️","Bilinmiyor"];
  return `<article class="card membership-summary"><p class="eyebrow">AKTİF ÜYELİK</p><h2>Aktif Aile Üyeliği</h2><div class="payment-facts"><span>Durum <strong>${status[0]} ${e(status[1])}</strong></span><span>Başlangıç <strong>${date(subscription.starts_at)}</strong></span><span>Bitiş <strong>${date(subscription.ends_at)}</strong></span><span>Kalan <strong>${daysLeft(subscription.ends_at)} gün</strong></span></div></article>`;
}

export function paymentHistory(payments) {
  if (!payments.length) return `<article class="card"><h2>Ödeme geçmişi</h2><p>Henüz ödeme talebi yok.</p></article>`;
  return `<section class="payment-history"><h2>Ödeme geçmişi</h2>${payments.map(row => {
    const effectiveStatus=effectivePaymentStatus(row),status = STATUS[effectiveStatus] || ["ℹ️",effectiveStatus]; const receipt = row.payment_receipts?.[0]; const sub = row.subscriptions?.[0],credit=Array.isArray(row.teacher_access_credits)?row.teacher_access_credits[0]:row.teacher_access_credits;const refunds=(row.refund_requests||[]).slice().sort((a,b)=>String(b.requested_at).localeCompare(String(a.requested_at))),refund=refunds[0];
    const teacherEligible=credit?.status==="active"&&new Date(credit.ends_at)>new Date(Math.max(Date.now(),new Date(credit.starts_at).getTime())),canRefund=effectiveStatus==="approved"&&Number(row.payable_amount)>0&&(!refund||["rejected","cancelled"].includes(refund.status))&&(row.plans?.code==="TEACHER_MONTHLY"?teacherEligible:(sub?.status==="active"&&new Date(sub.ends_at)>new Date()));
    const refundSummary=refund?`<section class="refund-summary"><span class="status-badge">${e(REFUND_STATUS[refund.status]||refund.status)}</span><dl><div><dt>Talep tarihi</dt><dd>${dateTime(refund.requested_at)}</dd></div><div><dt>İade tutarı</dt><dd>${money(refund.refund_amount)}</dd></div><div><dt>Neden</dt><dd>${e(refund.requested_reason)}</dd></div>${refund.admin_note?`<div><dt>Yönetici notu</dt><dd>${e(refund.admin_note)}</dd></div>`:""}${refund.completed_at?`<div><dt>Tamamlanma</dt><dd>${dateTime(refund.completed_at)}</dd></div>`:""}${refund.refund_reference?`<div><dt>İade referansı</dt><dd>${e(refund.refund_reference)}</dd></div>`:""}</dl></section>`:"";
    const refundBlock=refundSummary+(canRefund?`<section class="refund-request"><h4>Tam iade</h4><p>İade tutarı: <strong>${money(row.payable_amount)}</strong>. Tutar değiştirilemez. Para yönetici onayından sonra gerçekten gönderildiğinde iade tamamlanır ve ilgili kalan erişim sona erer.</p><label class="field">İade nedeni<textarea data-refund-reason minlength="10" maxlength="1000" required></textarea></label><button class="button danger" data-action="request-refund">İade talep et</button><p data-refund-status aria-live="polite"></p></section>`:effectiveStatus==="approved"&&!refund?`<p class="meta">Bu dönem otomatik iade için uygun değil.</p>`:"");
    return `<article class="card payment-history-row" data-payment-id="${e(row.id)}"><div><span class="status-badge status-${e(effectiveStatus)}">${status[0]} ${e(status[1])}</span><h3>${e(row.payment_code)}</h3><p>${e(planName(row.plans))} · ${money(row.payable_amount)}</p></div><dl><div><dt>Oluşturuldu</dt><dd>${date(row.created_at)}</dd></div>${effectiveStatus==="pending"?`<div><dt>Son geçerlilik tarihi</dt><dd>${dateTime(row.expires_at)}</dd></div><div><dt>Talep süresi</dt><dd>72 saat</dd></div><div><dt>Kalan süre</dt><dd>${e(remainingTime(row.expires_at))}</dd></div>`:""}<div><dt>Sonuçlandı</dt><dd>${date(row.reviewed_at||row.expired_at)}</dd></div><div><dt>Yöntem</dt><dd>${row.payment_method === "instagram" ? "Instagram" : "Site içi dekont / Havale"}</dd></div><div><dt>Dekont</dt><dd>${receipt ? `${e(receipt.original_filename)} · ${formatBytes(receipt.size_bytes)}` : "Henüz yok"}</dd></div><div><dt>Üyelik süresi</dt><dd>${sub ? `${date(sub.starts_at)} – ${date(sub.ends_at)}` : "—"}</dd></div></dl>${row.admin_note ? `<p class="feedback incorrect"><strong>Yönetici notu:</strong> ${e(row.admin_note)}</p>` : ""}${refundBlock}${["pending","receipt_sent"].includes(effectiveStatus) ? receiptUpload(row) : effectiveStatus==="expired"?`<div class="feedback incorrect"><p>Bu talebin 72 saatlik süresi doldu. Dekont ve Instagram bildirimi kapatıldı.</p><button class="button primary" data-action="new-payment-request">Yeni ödeme talebi oluştur</button></div>`:""}</article>`;
  }).join("")}</section>`;
}

function receiptUpload(row) {
  return `<section class="receipt-panel"><h4>Önerilen: Dekontu güvenli yükle</h4><label class="field">PDF, JPG veya PNG · en fazla 10 MB<input type="file" data-receipt-file accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png"></label><p data-file-summary class="meta">Dosya seçilmedi.</p><progress data-upload-progress max="100" value="0">0%</progress><div class="button-row"><button class="button primary" data-action="upload-receipt" data-payment-id="${e(row.id)}">Dekontu yükle</button>${row.payment_method === "instagram" && row.status === "pending" ? `<button class="button secondary" data-action="instagram-sent" data-payment-id="${e(row.id)}">Dekontu Instagram’dan gönderdim</button>` : ""}</div><p data-receipt-status aria-live="polite"></p></section>`;
}

export function paymentCenterView({ plans, subscription, payments }) {
  return `<section class="payment-center" data-route-page="membership"><div class="page-head"><div><p class="eyebrow">ÜYELİK VE ÖDEMELER</p><h1>Üyeliğini yönet</h1><p class="lead">Planını canlı fiyatlarla seç, ödeme kodunu al ve dekontunu güvenli yükle.</p></div><button class="button secondary" data-route="account">Hesaba dön</button></div>${subscriptionCard(subscription)}<section><h2>Planlar</h2><div class="payment-plan-grid">${planCards(plans)}</div></section><section class="card payment-request-panel" data-payment-request hidden><h2 data-request-title>Ödeme talebi</h2><form data-payment-form><input type="hidden" name="planCode"><div class="field"><label>Dekont yöntemi</label><select name="paymentMethod"><option value="bank_transfer">Site içinden güvenli dekont yükle (önerilen)</option><option value="instagram">Instagram’dan gönder</option></select></div><div class="field"><label>Kupon kodu (isteğe bağlı)</label><div class="inline-field"><input name="couponCode" maxlength="32" autocomplete="off"><button type="button" class="button secondary" data-action="validate-coupon">Kuponu doğrula</button></div></div><p data-coupon-result aria-live="polite"></p><div class="field"><label>Öğretmen / Davet Kodu (isteğe bağlı)</label><div class="inline-field"><input name="partnerCode" maxlength="24" autocomplete="off"><button type="button" class="button secondary" data-action="validate-partner-code">Kodu doğrula</button></div><small>Partner kodu fiyatı değiştirmez; kuponla birlikte kullanılabilir.</small></div><p data-partner-result aria-live="polite"></p><button class="button primary" data-action="create-payment">Ödeme talebi oluştur</button></form><div data-payment-result></div></section>${paymentHistory(payments)}</section>`;
}

export function paymentResult(row, instructions = PAYMENT_INSTRUCTIONS) {
  const bank = hasPaymentInstructions(instructions) ? `<section class="bank-transfer-card" aria-labelledby="bank-transfer-title"><p class="eyebrow">GÜVENLİ MANUEL ÖDEME</p><h3 id="bank-transfer-title">Banka Havale Bilgileri</h3><dl><div><dt>Banka adı</dt><dd>${e(instructions.bankName)}</dd></div><div><dt>Hesap sahibi</dt><dd>${e(instructions.accountHolder)}</dd></div><div><dt>IBAN</dt><dd class="bank-copy-row"><span data-copy-iban-value>${e(formatIban(instructions.iban))}</span><button type="button" class="button secondary" data-action="copy-iban">IBAN’ı Kopyala</button></dd></div><div><dt>Ödenecek tutar</dt><dd>${money(row.payable_amount)}</dd></div><div><dt>Ödeme kodu</dt><dd class="bank-copy-row"><span class="payment-code" data-copy-payment-code>${e(row.payment_code)}</span><button type="button" class="button secondary" data-action="copy-payment-code">Ödeme Kodunu Kopyala</button></dd></div></dl><p class="bank-transfer-warning">Havale/EFT açıklama alanına bu ödeme kodunu yazın: <strong>${e(row.payment_code)}</strong></p><p class="meta">Ödeme yaptıktan sonra dekontu site üzerinden yüklemenizi öneririz. Dekont göndermek ödeme onayı anlamına gelmez; üyeliğiniz yönetici ödemeyi onayladıktan sonra açılır.</p><p class="copy-status" data-copy-status aria-live="polite"></p></section>` : `<p class="feedback incorrect">Banka bilgileri henüz tanımlanmadı.</p>`;
  return `<article class="payment-created"><p class="feedback correct">✅ Ödeme talebin oluşturuldu.</p><p><strong>72 saat geçerli:</strong> ${dateTime(row.expires_at)} tarihine kadar dekont veya Instagram bildirimi gönderebilirsin.</p>${Number(row.payable_amount) === 0 ? `<p>Bu talep ödeme gerektirmiyor; üyelik incelemesi bekleniyor.</p>` : bank}</article>`;
}

export function adminPaymentsView(rows, { status="pending", search="" } = {}) {
  const visible = rows.filter(x => (status === "all" || x.status === status) && (!search || x.payment_code.toLowerCase().includes(search.toLowerCase())));
  return `<section class="payment-center admin-payments" data-route-page="admin-payments"><div class="page-head"><div><p class="eyebrow">YÖNETİCİ · ÖDEMELER</p><h1>Ödeme inceleme</h1></div><button class="button secondary" data-route="account">Hesaba dön</button></div><section class="card admin-payment-tools"><label>Durum<select data-admin-status><option value="pending" ${status==="pending"?"selected":""}>Bekleyen</option><option value="receipt_sent" ${status==="receipt_sent"?"selected":""}>Dekont gönderildi</option><option value="approved" ${status==="approved"?"selected":""}>Onaylandı</option><option value="rejected" ${status==="rejected"?"selected":""}>Reddedildi</option><option value="expired" ${status==="expired"?"selected":""}>Süresi doldu</option><option value="all" ${status==="all"?"selected":""}>Tümü</option></select></label><label>Ödeme kodu ara<input data-admin-search value="${e(search)}" placeholder="POMA-"></label></section><div class="admin-payment-list">${visible.length ? visible.map(adminRow).join("") : `<article class="card"><p>Bu filtrede ödeme yok.</p></article>`}</div></section>`;
}

export function adminRefundsView(rows=[]) {
  const group=(title,items)=>`<section class="card admin-refund-group"><h2>${title}</h2>${items.map(refundAdminRow).join("")||"<p>Kayıt yok.</p>"}</section>`;
  return `<section class="admin-refunds"><h1>İade yönetimi</h1>${group("Yeni iade talepleri",rows.filter(x=>x.refund_status==="requested"))}${group("Kabul edilmiş — para gönderimi bekleniyor",rows.filter(x=>x.refund_status==="approved"))}${group("İade geçmişi",rows.filter(x=>["completed","rejected","cancelled"].includes(x.refund_status)))}${group("Açık muhasebe uyarıları",rows.filter(x=>Number(x.accounting_alert_count)>0))}</section>`;
}
function refundAdminRow(row){
  const latestAlert=(row.accounting_alerts||[]).slice().sort((a,b)=>String(b.resolved_at||"").localeCompare(String(a.resolved_at||"")))[0],alertStatus=latestAlert?.status==="resolved"?"Çözüldü":"Açık";
  const completion=row.refund_status==="approved"?`<div class="refund-completion"><p><strong>Etki:</strong> Tam tutar gönderildiğinde bu döneme bağlı kalan erişim sonlandırılır; ödenmemiş komisyon iptal edilir, ödenmiş veya rezerve komisyon için muhasebe uyarısı açılır.</p><label class="field">İade yöntemi<select data-refund-method><option value="bank_transfer">Banka havalesi</option><option value="other">Diğer</option></select></label><label class="field">İade referansı<input data-refund-reference minlength="3" maxlength="200" required></label></div>`:"";
  const actions=row.refund_status==="requested"?`<button class="button primary" data-action="approve-refund">İadeyi kabul et</button><button class="button danger" data-action="reject-refund">Notla reddet</button>`:row.refund_status==="approved"?`<button class="button primary" data-action="complete-refund">İade tamamlandı</button><button class="button danger" data-action="cancel-refund">Kabul edilmiş talebi iptal et</button>`:"";
  const alert=latestAlert?`<section class="refund-accounting-alert"><p><strong>Muhasebe uyarısı:</strong> ${alertStatus} · ${e(latestAlert.alert_type)}</p><p>Komisyon: ${money(latestAlert.commission_amount)} · Earning: ${e(latestAlert.commission_earning_id)} · Payout: ${e(latestAlert.payout_id||"Yok")}</p>${latestAlert.resolution_note?`<p>Çözüm notu: ${e(latestAlert.resolution_note)}</p>`:""}</section>`:"";
  return `<article class="admin-refund-row" data-refund-id="${e(row.refund_request_id)}" data-alert-id="${e(row.accounting_alert_id||"")}"><h3>${e(row.payment_code)} · ${e(row.user_email)}</h3><p>${e(row.plan_name)} · Ödenen: ${money(row.payable_amount)} · İade: ${money(row.refund_amount)} · ${dateTime(row.payment_created_at)}</p><p><strong>${e(REFUND_STATUS[row.refund_status]||row.refund_status)}</strong> · Talep: ${dateTime(row.refund_requested_at)} · İnceleme: ${dateTime(row.refund_reviewed_at)} · Tamamlanma: ${dateTime(row.refund_completed_at)}</p><p>Neden: ${e(row.refund_reason)}</p><p>Etkilenecek erişim: ${e(row.entitlement_type)} · ${dateTime(row.access_ends_at)}</p><p>Komisyon: ${e(row.commission_status||"Yok")} · Açık muhasebe uyarısı: ${e(row.accounting_alert_count)}</p>${alert}${row.refund_admin_note?`<p>Yönetici notu: ${e(row.refund_admin_note)}</p>`:""}${completion}<label class="field">Yönetici notu<textarea data-refund-admin-note maxlength="1000"></textarea></label><div class="button-row">${actions}${Number(row.accounting_alert_count)>0?`<button class="button secondary" data-action="resolve-refund-alert">Muhasebe uyarısını çöz</button>`:""}</div><p data-refund-admin-status aria-live="polite"></p></article>`;
}

function adminRow(row) {
  const status = STATUS[row.status] || ["ℹ️",row.status]; const receipt = row.receipts?.[0];
  const deliveryLabels={pending:"E-posta bekliyor",processing:"E-posta gönderiliyor",sent:"E-posta gönderildi",failed:"E-posta gönderilemedi"};
  const delivery=["approved","rejected"].includes(row.status)&&row.email_delivery_id?`<section class="admin-email-delivery"><p><strong>E-posta:</strong> ${e(deliveryLabels[row.email_delivery_status]||row.email_delivery_status||"Bilinmiyor")}${row.email_delivery_status==="sent"&&row.email_delivery_sent_at?` · ${dateTime(row.email_delivery_sent_at)}`:""}</p>${["pending","failed"].includes(row.email_delivery_status)?`<button class="button secondary" data-action="retry-payment-email">E-postayı yeniden gönder</button>`:""}<p data-email-action-status aria-live="polite"></p></section>`:"";
  return `<article class="card admin-payment-row" data-payment-id="${e(row.id)}"><div class="admin-payment-head"><div><span class="status-badge status-${e(row.status)}">${status[0]} ${e(status[1])}</span><h2>${e(row.payment_code)}</h2><p>${e(row.user_email)} · ${e(row.plan_name)}</p></div><strong>${money(row.payable_amount)}</strong></div><div class="payment-facts"><span>Liste fiyatı <strong>${money(row.list_price)}</strong></span><span>İndirim <strong>${money(row.discount_amount)}</strong></span><span>Yöntem <strong>${row.payment_method === "instagram" ? "Instagram" : "Havale / site içi"}</strong></span><span>Oluşturuldu <strong>${date(row.created_at)}</strong></span><span>Son geçerlilik <strong>${dateTime(row.expires_at)}</strong></span><span>Mevcut üyelik bitişi <strong>${date(row.current_subscription_ends_at)}</strong></span></div>${receipt ? `<button class="button secondary" data-action="open-admin-receipt">Dekontu güvenli aç</button>` : `<p class="meta">Dekont dosyası yok.</p>`}${["pending","receipt_sent"].includes(row.status) ? `<div class="admin-review"><label class="field">Yönetici notu<textarea data-admin-note rows="2"></textarea></label><div class="button-row"><button class="button primary" data-action="approve-payment">Ödemeyi onayla</button><button class="button danger" data-action="reject-payment">Notla reddet</button></div><p data-review-status aria-live="polite"></p></div>` : row.status==="expired"?`<p class="meta">Süresi dolan talep için yönetici işlemi yoktur.</p>`:row.admin_note ? `<p>Yönetici notu: ${e(row.admin_note)}</p>` : ""}${delivery}</article>`;
}

export function formatBytes(bytes) { const n=Number(bytes||0); return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`; }
export function formatIban(value) { return String(value || "").replace(/\s+/g, "").replace(/(.{4})(?=.)/g, "$1 "); }
export function validateReceiptFile(file) {
  if (!file || !["application/pdf","image/jpeg","image/png"].includes(file.type)) throw new Error("PDF, JPG veya PNG dosyası seç.");
  if (!file.size || file.size > 10*1024*1024) throw new Error("Dosya en fazla 10 MB olabilir.");
  return true;
}
