import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import {selectAdaptiveSportWords,sportLessonNumber} from "../js/sport-question-engine.js";
const words=Array.from({length:36},(_,i)=>{const lesson=Math.floor(i/6);return{id:`w${i}`,word:`word${i}`,meaningTr:`anlam${i}`,example:`This is word ${i}.`,lessonId:`${String(lesson).padStart(3,"0")}-lesson`}}),progress=()=>({recentQuestionIds:[],words:{}}),select=(state={},p=progress())=>selectAdaptiveSportWords(words,state,p,()=>0.37,10),source=file=>fs.readFileSync(new URL(`../js/${file}`,import.meta.url),"utf8");
test("ilerlemesi olmayan çocuk başlangıç havuzunu alır",()=>{const rows=select();assert.equal(rows.length,10);assert.equal(rows.every(row=>sportLessonNumber(row)<=2),true);});
test("ilerlemiş çocuk açılmış derslerden soru alır",()=>{const rows=select({lessonProgress:{"003-lesson":{completed:true}}});assert.equal(rows.filter(row=>sportLessonNumber(row)===3).length,6);});
test("görülmemiş ileri konu ana havuza girmez",()=>{const rows=select({lessonProgress:{"003-lesson":{currentScreen:2}}});assert.equal(rows.some(row=>sportLessonNumber(row)>4),false);assert.equal(rows.filter(row=>sportLessonNumber(row)===4).length<=1,true);});
test("önceki ders tekrarları dağılımda bulunur",()=>{const rows=select({lessonProgress:{"003-lesson":{completed:true}}});assert.equal(rows.filter(row=>sportLessonNumber(row)<3).length>=3,true);});
test("son beş soru gereksiz tekrar edilmez",()=>{const recent=words.slice(6,11).map(row=>row.id),rows=select({}, {recentQuestionIds:recent,words:{}});assert.equal(rows.some(row=>recent.includes(row.id)),false);});
test("ilerleme verisi okunamazsa başlangıç havuzuna güvenli dönülür",()=>{const broken={get lessonProgress(){throw new Error("unreadable")}},rows=select(broken);assert.equal(rows.length,10);assert.equal(rows.every(row=>sportLessonNumber(row)<=2),true);});
test("futbol ve voleybol aynı seçim motorunu ve idempotent öğrenme olaylarını kullanır",()=>{const football=source("football-engine.js"),volleyball=source("volleyball-engine.js"),footballGame=source("football-game.js"),volleyballGame=source("volleyball-game.js"),sync=source("sync-engine.js");assert.match(football,/selectAdaptiveSportWords/);assert.match(volleyball,/createFootballMatchQuestions/);assert.match(footballGame,/recordSportAnswer/);assert.match(volleyballGame,/recordSportAnswer/);assert.match(sync,/sportLearningEvents/);assert.match(football,/idempotencyKey:`sport:/);});
