import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { learningReportView } from "../js/learning-report-views.js";
import { reportPeriod } from "../js/report-periods.js";

const entry=fs.readFileSync(new URL("../js/learning-report-entry.js",import.meta.url),"utf8"),css=fs.readFileSync(new URL("../css/learning-reports.css",import.meta.url),"utf8");
const scopedFiles=["learning-report-entry.js","learning-report-service.js","learning-report-views.js","report-periods.js"].map(name=>fs.readFileSync(new URL(`../js/${name}`,import.meta.url),"utf8"));
const base={children:[{id:"a",name:"Ayşe"},{id:"b",name:"Bora"}],selectedChildId:"a",reportType:"weekly",rows:[]};
test("report center renders child selector, period tabs and real summary",()=>{const html=learningReportView({...base,rows:[{id:"r1",child_name:"Ayşe",period_start:"2026-07-06T00:00:00Z",period_end:"2026-07-13T00:00:00Z",metrics:{completed_lessons:2,questions_answered:10,accuracy_percent:80},strengths:[{topic_key:"Zamirler"}],practice_recommendations:["Kısa tekrar"]}]});assert.match(html,/Ayşe/);assert.match(html,/Bora/);assert.match(html,/Haftalık/);assert.match(html,/Tamamlanan ders/);assert.match(html,/%80/);assert.match(html,/Zamirler/);});
test("empty report hides invented metrics and explains missing weekly event data",()=>{const html=learningReportView(base);assert.match(html,/Bu dönem için henüz rapor oluşmadı/);assert.doesNotMatch(html,/Doğruluk<\/span><strong>%0/);});
test("multi-child changes load the selected child's isolated payload",()=>{assert.match(entry,/event\.target\.matches\("\[data-report-child\]"\)[\s\S]*state\.childId=event\.target\.value[\s\S]*await loadReports/);assert.match(entry,/const token=\+\+renderToken/);assert.match(entry,/if\(token!==renderToken\)return/);});
test("student role is rejected before report service calls",()=>{assert.match(entry,/!\["parent","both"\]\.includes\(account\.profile\?\.account_type\)/);assert.match(entry,/yalnız veli hesaplarına açıktır/);});
test("print view hides navigation and uses A4",()=>{assert.match(css,/@page\{size:A4/);assert.match(css,/@media print/);assert.match(css,/\.topbar[^}]*display:none!important/);});
test("responsive report cards collapse without horizontal tables",()=>{assert.match(css,/@media\(max-width:820px\)\{\.report-metrics,\.report-sections\{grid-template-columns:1fr\}/);assert.doesNotMatch(css,/overflow-x:auto/);});
test("signed-out landing does not call report RPCs",()=>{assert.match(entry,/if\(account\.status!=="signed-in"\)return navigate\("login"\)/);assert.match(entry,/if\(getRoute\(\)==="parent\/reports"\)openReportCenter\(\)/);});
test("learning report strings are valid UTF-8 without mojibake",()=>{for(const source of [...scopedFiles,css])assert.doesNotMatch(source,/Ã.|Å.|Ä.|â€|Â./);assert.match(scopedFiles.join("\n"),/Gelişim Raporları/);});
test("learning report source and dist assets are identical",()=>{for(const name of ["learning-report-entry.js","learning-report-service.js","learning-report-views.js","report-periods.js"])assert.deepEqual(fs.readFileSync(new URL(`../js/${name}`,import.meta.url)),fs.readFileSync(new URL(`../dist/js/${name}`,import.meta.url)));assert.deepEqual(fs.readFileSync(new URL("../css/learning-reports.css",import.meta.url)),fs.readFileSync(new URL("../dist/css/learning-reports.css",import.meta.url)));});
test("release indexes and service workers include report assets",()=>{assert.deepEqual(fs.readFileSync(new URL("../index.html",import.meta.url)),fs.readFileSync(new URL("../dist/index.html",import.meta.url)));const sw=fs.readFileSync(new URL("../service-worker.js",import.meta.url),"utf8");for(const asset of ["css/learning-reports.css","js/report-periods.js","js/learning-report-service.js","js/learning-report-views.js","js/learning-report-entry.js"])assert.match(sw,new RegExp(asset.replaceAll(".","\\.")));});
