import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {renderMonthlyParentReport} from "../supabase/functions/_shared/monthly-parent-report.mjs";
const sql=fs.readFileSync(new URL("../supabase/migrations/20260721000100_monthly_parent_progress_reports.sql",import.meta.url),"utf8");
const edge=fs.readFileSync(new URL("../supabase/functions/send-weekly-parent-reports/index.ts",import.meta.url),"utf8");
const service=fs.readFileSync(new URL("../js/learning-report-service.js",import.meta.url),"utf8");
const views=fs.readFileSync(new URL("../js/learning-report-views.js",import.meta.url),"utf8");
const report=(name="Ayşe",metrics={active_weeks:3,active_days:8,lessons_completed:4,questions_answered:12,accuracy_percent:75,games_completed:2,stories_completed:1})=>({child_name:name,metrics,topics_studied:["selamlaşma"],improved_topics:[{topic_key:"kelimeler"}],review_topics:[{topic_key:"sorular"}]});

test("ay sınırları Europe/Istanbul takvim ayıdır",()=>{assert.match(sql,/date_trunc\('month',p_reference at time zone 'Europe\/Istanbul'\)-interval '1 month'/);assert.match(sql,/p_period_start::timestamp at time zone 'Europe\/Istanbul'/);});
test("aynı çocuk ve ay için ikinci snapshot oluşmaz",()=>{assert.match(sql,/unique\(child_id,period_start,report_version\)/);assert.match(sql,/on conflict\(child_id,period_start,report_version\) do nothing/);});
test("aynı velinin çocukları tek aylık digest içinde birleşir",()=>{assert.match(sql,/jsonb_agg\(jsonb_build_object[\s\S]*order by child_name/);const m=renderMonthlyParentReport({period_start:"2026-06-30T21:00:00Z",reports:[report("Ayşe"),report("Bora")]});assert.match(m.text,/Ayşe[\s\S]*Bora/);assert.equal((m.html.match(/<section/g)||[]).length,2);});
test("başka velinin çocuğu aylık rapora karışmaz",()=>{assert.match(sql,/where parent_user_id=r\.guardian_id and period_start=b\.period_start/);assert.match(sql,/g\.guardian_id=p_parent_user_id/);});
test("aylık toplam mevcut haftalık snapshot metriklerinden hesaplanır",()=>{assert.match(sql,/with w as\(select metrics from public\.student_weekly_reports/);for(const key of ["active_weeks","active_days","lessons_completed","questions_answered","correct_answers","games_completed","stories_completed"])assert.match(sql,new RegExp(`'${key}'`));});
test("veri yokken oran veya çalışma süresi uydurulmaz",()=>{assert.match(sql,/accuracy_percent',case when coalesce\(sum\(\(metrics->>'questions_answered'\)::int\),0\)>=5/);assert.match(sql,/duration_seconds',null/);const m=renderMonthlyParentReport({period_start:"2026-06-30T21:00:00Z",reports:[report("Ayşe",{accuracy_percent:null})]});assert.doesNotMatch(m.text,/%0/);});
test("konu değerlendirmesi ve ay karşılaştırması en az beş cevaba bağlıdır",()=>{assert.equal((sql.match(/answers>=5/g)||[]).length>=3,true);assert.match(sql,/prev\.answers>=5/);assert.doesNotMatch(sql,/başarısız|zayıf|geri kaldı/i);});
test("aylık opt-out raporu korur ve delivery skipped olur",()=>{assert.match(sql,/monthly_progress_email_enabled/);assert.match(sql,/case when not v_opt[\s\S]*then 'skipped'/);assert.match(sql,/parent_opted_out/);});
test("feature flag kapalı başlar ve aylık cron ilk Pazartesi 10:00 içindir",()=>{assert.match(sql,/monthly_parent_reports_enabled',false/);assert.match(sql,/extract\(day from now\(\) at time zone 'Europe\/Istanbul'\)>7/);assert.match(sql,/cron\.schedule\('monthly-parent-reports-v1','0 7 \* \* 1'/);assert.match(edge,/monthly_job_token[\s\S]*service_claim_monthly_parent_report_job/);assert.match(edge,/Idempotency-Key[^\n]*monthly[^\n]*parent-report\/\$\{delivery\.id\}/);});
test("veli sahipliği, admin kapısı, RLS ve UI aylık geçmiş/tercih akışı kapalıdır",()=>{assert.match(sql,/parents read own monthly reports[\s\S]*parent_user_id=\(select auth\.uid\(\)\)/);assert.match(sql,/list_admin_monthly_report_deliveries[\s\S]*if not public\.is_poma_admin\(\)/);assert.match(sql,/revoke all on table public\.student_monthly_reports from public,anon,authenticated,service_role/);assert.match(service,/listMonthly[\s\S]*getMonthlyPreference[\s\S]*setMonthlyPreference/);assert.match(views,/data-\$\{reportType\}-email-preference/);});
