import fs from "node:fs";import path from "node:path";import crypto from "node:crypto";import {fileURLToPath} from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."),dist=path.join(root,"dist"),curriculum=JSON.parse(fs.readFileSync(path.join(root,"data/curriculum.json"),"utf8")),config=JSON.parse(fs.readFileSync(path.join(root,"data/app-config.json"),"utf8"));
const lessonFiles=curriculum.modules.flatMap(m=>m.lessons).filter(l=>l.status==="published").map(l=>l.file);
const reviewFiles=Object.values(config.moduleReviews||{});
function walk(dir){return fs.existsSync(path.join(root,dir))?fs.readdirSync(path.join(root,dir),{withFileTypes:true}).flatMap(e=>{const p=path.join(dir,e.name).replace(/\\/g,"/");return e.isDirectory()?walk(p):[p]}):[]}
const footballAssets=walk("assets/games/poma-football-v1");
const base=["index.html","manifest.webmanifest","css/reset.css","css/variables.css","css/app.css","css/responsive.css","css/sprint2.css","css/quality.css","css/print.css","css/football.css","js/app.js","js/router.js","js/storage.js","js/scoring.js","js/catalog.js","js/audio.js","js/accessibility.js","js/lesson-engine.js","js/diagnostic-engine.js","js/activity-renderers.js","js/parent-mode.js","js/review-engine.js","js/vocabulary-engine.js","js/poma-assets.js","js/football-engine.js","js/football-audio.js","js/football-game.js","data/app-config.json","data/curriculum.json","data/diagnostic-test.json",...reviewFiles,"data/vocabulary.json","assets/icons/icon.svg",...footballAssets,...lessonFiles];
for(const f of base)if(!fs.existsSync(path.join(root,f)))throw new Error(`Build dosyası eksik: ${f}`);
const version=crypto.createHash("sha256").update(base.map(f=>fs.readFileSync(path.join(root,f))).join("|")).digest("hex").slice(0,12);
const sw=`const CACHE="beyza-english-${version}";\nconst ASSETS=${JSON.stringify(["./",...base],null,2)};\nself.addEventListener("install",e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));\nself.addEventListener("activate",e=>e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==CACHE).map(x=>caches.delete(x)))).then(()=>self.clients.claim())));\nself.addEventListener("message",e=>{if(e.data?.type==="SKIP_WAITING")self.skipWaiting()});\nself.addEventListener("fetch",e=>{if(e.request.method!=="GET")return;e.respondWith(caches.match(e.request).then(x=>x||fetch(e.request).then(r=>{const q=r.clone();caches.open(CACHE).then(c=>c.put(e.request,q));return r}).catch(()=>caches.match("index.html"))))});\n`;
fs.writeFileSync(path.join(root,"service-worker.js"),sw,"utf8");fs.mkdirSync(dist,{recursive:true});for(const x of fs.readdirSync(dist))fs.rmSync(path.join(dist,x),{recursive:true,force:true});
for(const f of [...base,"service-worker.js","START_APP.bat","server.py","server.js","README_KULLANIM.md"]){const src=path.join(root,f),dst=path.join(dist,f);fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(src,dst)}
console.log(`Build ${version}: ${lessonFiles.length} ders, ${base.length} önbellek öğesi.`);
