import fs from "node:fs";import path from "node:path";import crypto from "node:crypto";import {fileURLToPath} from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."),dist=path.join(root,"dist"),curriculum=JSON.parse(fs.readFileSync(path.join(root,"data/curriculum.json"),"utf8")),config=JSON.parse(fs.readFileSync(path.join(root,"data/app-config.json"),"utf8"));
const lessonFiles=curriculum.modules.flatMap(m=>m.lessons).filter(l=>l.status==="published").map(l=>l.file);
const reviewFiles=Object.values(config.moduleReviews||{});
function walk(dir){return fs.existsSync(path.join(root,dir))?fs.readdirSync(path.join(root,dir),{withFileTypes:true}).flatMap(e=>{const p=path.join(dir,e.name).replace(/\\/g,"/");return e.isDirectory()?walk(p):[p]}):[]}
const footballAssets=walk("assets/games/poma-football-v1");
const volleyballAssets=walk("assets/games/poma-volleyball-v1");
const storyAssets=walk("assets/stories");
const sportAudioAssets=walk("assets/audio");
const brandAssets=walk("assets/brand");
const base=["index.html","manifest.webmanifest","css/reset.css","css/variables.css","css/app.css","css/responsive.css","css/sprint2.css","css/quality.css","css/print.css","css/football.css","css/story.css","js/app.js","js/router.js","js/storage.js","js/account-config.js","js/account-storage.js","js/supabase-client.js","js/student-repository.js","js/teacher-repository.js","js/sync-engine.js","js/account-session.js","js/account-views.js","js/scoring.js","js/catalog.js","js/audio.js","js/accessibility.js","js/lesson-engine.js","js/diagnostic-engine.js","js/activity-renderers.js","js/parent-mode.js","js/review-engine.js","js/vocabulary-engine.js","js/poma-assets.js","js/volleyball-assets.js","js/sport-media.js","js/football-engine.js","js/football-audio.js","js/football-game.js","js/volleyball-engine.js","js/volleyball-game.js","js/story-engine.js","js/story-view.js","data/app-config.json","data/curriculum.json","data/diagnostic-test.json",...reviewFiles,"data/vocabulary.json","data/stories/story-001.json","assets/icons/icon.svg",...footballAssets,...volleyballAssets,...storyAssets,...sportAudioAssets,...brandAssets,...lessonFiles];
base.splice(base.indexOf("css/print.css"), 0, "css/profile-menu.css");
base.splice(base.indexOf("js/student-repository.js"), 0, "js/payment-service.js");
for(const f of base)if(!fs.existsSync(path.join(root,f)))throw new Error(`Build dosyası eksik: ${f}`);
const version=crypto.createHash("sha256").update(base.map(f=>fs.readFileSync(path.join(root,f))).join("|")).digest("hex").slice(0,12);
const heavyMediaPrefixes=["assets/games/","assets/stories/","assets/audio/","assets/brand/"];
const precache=["./",...base.filter(f=>!heavyMediaPrefixes.some(prefix=>f.startsWith(prefix)))];
const sw=`const CACHE="beyza-english-${version}";\nconst ASSETS=${JSON.stringify(precache,null,2)};\nself.addEventListener("install",e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));\nself.addEventListener("activate",e=>e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==CACHE).map(x=>caches.delete(x)))).then(()=>self.clients.claim())));\nself.addEventListener("message",e=>{if(e.data?.type==="SKIP_WAITING")self.skipWaiting()});\nself.addEventListener("fetch",e=>{if(e.request.method!=="GET")return;const u=new URL(e.request.url);if(u.origin!==self.location.origin){e.respondWith(fetch(e.request));return}e.respondWith(caches.match(e.request).then(x=>x||fetch(e.request).then(r=>{if(!r||!r.ok)return r;const q=r.clone();caches.open(CACHE).then(c=>c.put(e.request,q));return r}).catch(()=>e.request.mode==="navigate"?caches.match("index.html"):Response.error())))});\n`;
fs.writeFileSync(path.join(root,"service-worker.js"),sw,"utf8");fs.mkdirSync(dist,{recursive:true});for(const x of fs.readdirSync(dist))fs.rmSync(path.join(dist,x),{recursive:true,force:true});
for(const f of [...base,"service-worker.js","START_APP.bat","server.py","server.js","README_KULLANIM.md"]){const src=path.join(root,f),dst=path.join(dist,f);fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(src,dst)}
console.log(`Build ${version}: ${lessonFiles.length} ders, ${precache.length} başlangıç önbelleği, ${base.length-precache.length+1} isteğe bağlı medya.`);
